name: dlna
description: A simple DLNA DMC library implemented by Dart. It is tiny and only the most basic network video casting function is supported.
homepage: https://github.com/succlz123/DLNA-Dart
version: 0.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^0.4.8
  xml2json: ^4.2.0
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
